name: infinite_horizons
description: "Using this app your study and work session efficiency can increase dramatically by following research-based methods."
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_line_through: ^1.0.4
  animated_text_kit:
    git:
      url: https://github.com/guyluz11/Animated-Text-Kit.git
      ref: master
  animated_toggle_switch: ^0.8.2
  audioplayers: ^6.0.0
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  collection: ^1.18.0
  # Blast confetti
  confetti: ^0.7.0
  # Cupertino Icons font to your application
  cupertino_icons: ^1.0.8
  # Make an animated circular countdown
  custom_timer: ^0.2.3
  device_info_plus: ^10.1.0
  # Internationalization (Easy translations)
  do_not_disturb: ^1.0.3
  easy_localization: ^3.0.6
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.2
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.10+1
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  health: ^10.2.0
  introduction_screen:
    git:
      url: https://github.com/guyluz11/introduction_screen.git
      ref: master
  liquid_progress_indicator_v2: ^0.5.0
  # Logger which prints beautiful logs
  logger: ^2.2.0
  permission_handler: ^11.3.1
  progress_tracker:
    git:
      url: https://github.com/guyluz11/progress-tracker.git
      ref: main
  shared_preferences: ^2.2.3
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  vibration: ^2.0.1
  wakelock_plus: ^1.2.5
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  # Simplifies the task of updating your Flutter app's launcher icon
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.3.0
  test: ^1.24.9



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/sound_effects/
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#061E4A"
